/*
 * Copyright (c) 2025 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work
 * except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the Licence for the specific language
 * governing permissions and limitations under the Licence.
 */
import SwiftUI

public enum LocalizableStringKey: Equatable, Sendable {
  case dynamic(key: String)
  case custom(String)

  /*
  case space
  case search
  case genericErrorTitle
  case genericErrorDesc
  case biometryOpenSettings
  case biometryConfirmRequest
  case invalidQuickPin
  case tryAgain
  case shareButton
  case cancelButton
  case requestDataCaption
  case requestDataInfoNotice
  case requestDataTitle([String])
  case documentAdded
  case requestDataSheetCaption
  case okButton
  case shareDataReview
  case success
  case successfullySharedFollowingInformation
  case incompleteRequestDataSelection
  case addDoc
  case filters
  case sortByIssuedDateSectionTitle
  case showResults
  case welcomeBack([String])
  case viewDocumentDetails
  case pleaseWait
  case requestDataShareQuickPinCaption
  case requestDataShareBiometryCaption
  case addDocumentTitle
  case addDocumentSubtitle
  case addDocumentRequest
  case proximityConnectivityCaption
  case unavailableField
  case requestDataVerifiedEntity
  case requestDataVerifiedEntityMessage
  case changeQuickPinOption
  case quickPinSetTitle
  case quickPinEnterPin
  case quickPinConfirmPin
  case quickPinSetCaptionOne
  case quickPinSetCaptionTwo
  case quickPinNextButton
  case quickPinConfirmButton
  case quickPinSetSuccess
  case loginTitle
  case loginCaptionQuickPinOnly
  case loginCaption
  case quickPinSetSuccessButton
  case quickPinDoNotMatch
  case quickPinUpdateTitle
  case quickPinUpdateCaptionOne
  case quickPinUpdateCaptionTwo
  case quickPinUpdateCaptionThree
  case quickPinUpdateSuccess
  case quickPinUpdateSuccessButton
  case quickPinUpdateCancellationTitle
  case quickPinUpdateCancellationCaption
  case quickPinUpdateCancellationContinue
  case successTitlePunctuated
  case issuerWantWalletAddition
  case unknownVerifier
  case unknownIssuer
  case genericIssuer
  case filterByIssuer
  case yes
  case no
  case scanQrCode
  case signDocument
  case signDocumentSubtitle
  case selectDocument
  case validUntil([String])
  case bleDisabledModalTitle
  case bleDisabledModalCaption
  case bleDisabledModalButton
  case requestDataNoDocument
  case issuanceDetailsDeletionTitle([String])
  case deleteDocument
  case issuanceDetailsDeletionCaption([String])
  case errorUnableFetchDocuments
  case errorUnableFetchDocument
  case scannerQrTitleIssuing
  case scannerQrTitlePresentation
  case scannerQrCaptionIssuing
  case scannerQrCaptionPresentation
  case scannerQrTitle
  case scannerQrCaption
  case cameraError
  case missingPid
  case requestCredentialOfferTitle([String])
  case requestCredentialOfferNoDocument
  case unableToIssueAndStore
  case missingMetadata
  case issueButton
  case issuanceCodeTitle([String])
  case issuanceCodeCaption([String])
  case transactionCodeFormatError([String])
  case inProgress
  case scopedIssuanceSuccessDeferredCaption
  case scopedIssuanceSuccessDeferredCaptionDocName([String])
  case scopedIssuanceSuccessDeferredCaptionDocNameAndIssuer([String])
  case issuanceSuccessDeferredCaption([String])
  case pending
  case issuanceFailed
  case deferredDocumentsIssuedModalTitle
  case defferedDocumentsIssuedModalCaption
  case retrieveLogs
  case qrScanInformativeText
  case unableToPresentAndShare
  case itemNotFoundInStorage
  case itemsNotFoundInStorage
  case home
  case documents
  case transactions
  case authenticateAuthoriseTransactions
  case electronicallySignDigitalDocuments
  case learnMore
  case chooseFromList
  case chooseFromListTitle

  // Settings
  case settingsSupport
  case settingsUnlockWithBiometrics
  case settingsLanguage
  case settingsDeleteAllProofsOfAttestation
  case settingsTermsOfService
  case settingsAboutThisApp

  case addDocumentsToWallet
  case details
  case dataSharingRequest
  case dataShared
  case doneButton
  case dataSharingTitle
  case close
  case reset
  case all
  case descending
  case ascending
  case trustedRelyingParty
  case trustedRelyingPartyDescription
  case alertAccessOnlineServices
  case alertAccessOnlineServicesMessage
  case alertSignDocumentsSafely
  case alertSignDocumentsSafelyMessage
  case authenticate
  case inPerson
  case online
  case savedToFavorites
  case succesfullyAddedFollowingToWallet
  case removedFromFavorites
  case savedToFavoritesMessage
  case removedFromFavoritesMessages
  case viewDetails
  case requestsTheFollowing
  case walletIsSecured
  case noResults
  case noResultsDocumentsDescription
  case noResultsTransactionsDescription
  case proximityConnectionBleDescription
  case selectExpiryPeriod
  case filterByState
  case sortBy
  case deleteDocumentConfirmDialog
  case defaultLabel
  case valid
  case revoke
  case expired
  case dateIssued
  case expiryDate
  case nextSevenDays
  case nextThirtyDays
  case beyondThiryDays
  case beforeToday
  case issuanceRequest
  case myEuWallet
  case categoryGovernment
  case categoryHealth
  case categoryEducation
  case categoryFinance
  case categoryRetail
  case categoryOther
  case categorySocialSecurity
  case categoryTravel
  case changelog
  case orderBy
  case filterByCategory
  case searchDocuments
  case searchTransactions
  case filterByStatus
  case completed
  case failed
  case filterByDate
  case startDate
  case endDate
  case relyingParty
  case signedDocuments
  case transactionInformation
  case transactionDetailsDataShare
  case transactionDetailsDataSigned
  case transactionDetailsScreenCardDateLabel
  case transactionDetailsCompleted
  case or
  case today
  case thisWeek
  case unknownDate
  case minutesAgo([String])
  case minuteAgo([String])
  case transactionDate
  case filterByType
  case presentation
  case signing
  case issuance
  case withoutRelyingName
  case errorFetchTransactionLog
  case settings

  // splash screen
  case splashTitle
  case splashSponsorsTitle

  // feature-onboarding
  case onboardingStepWelcome
  case onboardingStepConsent
  case onboardoingStepPin
  case onboardingStepEnrollment

  // welcome step
  case welcomeTitle1
  case welcomePage1
  case welcomeTitle2
  case welcomePage2
  case welcomeTitle3
  case welcomePage3
  case welcomeSkipButton

  // Consent Step
  case consentTitle
  case consentCheckboxLabel1
  case consentCheckboxLabel2
  case consentCheckboxLabel3
  case consentHyperlinkLabel1
  case consentHyperlinkLabel2
  case consentConfirmButton

  // Pin Setup Step
  case quickPinCreateTitle
  case quickPinReEnterTitle
  case quickPinCreateSubtitle
  case quickPinReEnterSubtitle
  case quickPinTitle

  // Verification Step
  case verificationStepTitle
  case verificationStepDescription
  case verificationNationalId
  case verificationNationalIdDescription

  // Landing screen
  case landingScreenTitle
  case landingScreenbody
  case europeanUnionLabel1
  case credentialDetailsTitle
  case scanTitle
  case landingCredentialsLeft(Int)
  case addMoreCredentials

  // Biometric Setup
  case biometricSetupTitle
  case biometricSetupDescription(String)
  case biometricSetupButton
  case biometricSetupSkipButton

  // Settings
  case settingsAppInformation
  case settingsAppVersion
  case settingsCredentials
  case settingsDeleteCredentials

  //generic
  case back

  // Quick Pin ( BiometryView )
  case quickPinInvalidWithAttempts(Int)
  case quickPinInvalidLastAttempt
  case quickPinLockedOut
  case quickPinLockoutCountdownMinutes([Int])
  case quickPinLockoutCountdownSeconds(Int)
  case quickPinErrorInsecurePin

  // Change Pin
  case changeQuickPinCaption
  case changePinDescription
  case changePinFirstPinDescription
  case changePinSecondPinDescription
  case changePinHelpText
  case changePinSuccessText

  // Credential Issuance
  case credentialIssuanceTitle
  case credentialIssuanceDescription

  case incomplete
  case justNow
  case revoked
  case documentDetailsRevokedDocumentMessage
  case revokedModalTitle
  case revokedModalDescription
  case transactionDetailsRequestDeletionMessage
  case transactionDetailsRequestDeletionButton
  case transactionDetailsReportTransactionMessage
  case transactionDetailsReportTransactionButton
  case documentDetailsDocumentCredentialsText([String])
  case documentDetailsDocumentCredentialsMoreInfoText
  case documentDetailsDocumentCredentialsExpandedTextSubtitle
  case documentDetailsDocumentCredentialsExpandedButtonHideText
  case documentsListCredentialsUsageText([String])
  case expandableDocumentCredentialsIssueButton
  case issuanceAddDocumentNoOptions
  case unknown
  case acceptButton
  case proofOfAgeTitle
  case documentProviderSectionHeader

  // Pasport Flow
  case passportIdentificationTitle
  case passportIdentificationDescription
  case passportIdentificationStepFirst
  case passportIdentificationStepSecond
  case passportIdentificationFooter
  case passportIdentificationBack
  case passportIdentificationCapture
  case passportCaptureTitle
  case passportCaptureSubtitle
  case passportIdentification
  case passportBiometrics
  case passportLiveVideo
  case passportBiometricsBack
  case passportBiometricsNext
  case passportBiometricsContentDescription
  case passportBiometricsFirstHeader
  case passportBiometricsFirstDescription
  case passportBiometricsFirstLink
  case passportBiometricsVerifyData
  case passportBiometricsTryAgain
  case passportBiometricsPassport
  case passportBiometricsDob
  case passportBiometricsDoe
  case passportBiometricsNoAvailability
  case passportBiometricsNoPassportData
  case passportBiometricsScanCancelled
  case passportBiometricsUnknownError
  case passportLiveVideoHeader
  case passportLiveVideoDescription
  case passportLiveVideoStepFirst
  case passportLiveVideoStepSecond
  case passportLiveVideoStepThird
  case passportLiveVideoFooter
  case passportLiveVideoBack
  case passportLiveVideoLiveCapture
  case passportLiveVideoErrorNotProcessed
  case passportLiveVideoErrorNotLive
  case passportLiveVideoErrorNotMatching
  case passportValidationErrorExpired
  case passportValidationErrorUnderage
  case passportValidationErrorIncompleteData
  case passportLiveVideoDownloadingProgress
  case passportCredentialIssuanceTitle
  case passportCredentialIssuanceDescription
  case consentScreenPersonalDataCheckbox
  case passportScanIntroEnrollmentMethod
  case passportScanIntroTitle
  case passportScanIntroDescription
  case passportScanIntroBackButton
  case passportScanIntroStartButton
  case passportScanIntroStep1Title
  case passportScanIntroStep1Description
  case passportScanIntroStep2Title
  case passportScanIntroStep2Description
  case passportScanIntroStep3Title
  case passportScanIntroStep3Description
  case passportScanIntroStep4Title
  case passportScanIntroStep5Title
  case passportScanIntroDataDownloadNotice
  case cdFlashButton
  case cdCloseButton
  case labelClose
  case labelTurnOn
  case nfcBodyInitial
  case nfcBodyReading
  case nfcHelpLink
  case nfcTitle
  case nfcTitleInitial
  case nfcTitleReading
  case requiredNfcNotSupported
  case requiredPermsNotGiven
  case warningAuthenticationFailed
  case warningClaNotSupported
  case warningEnableNfc
   */
  case biometricDefaultModeTextAbovePinField
  case biometricLoginBiometricsEnabledSubtitle
  case biometricLoginBiometricsNotEnabledSubtitle
  case biometricLoginForgotPin
  case biometricLoginTitle
  case biometricNoHardware
  case biometricPromptSubtitle
  case biometricPromptTitle
  case biometricSetupDescription(String)
  case biometricSetupEnable
  case biometricSetupSkip
  case biometricSetupTitle
  case biometricUnknownError
  case cdCloseButton
  case cdFlashButton
  case confirmDocRemovalDialogDelete
  case confirmDocRemovalDialogText
  case confirmDocRemovalDialogTitle
  case consentScreenConfirmButton
  case consentScreenDataProtectionButton
  case consentScreenDataProtectionCheckbox
  case consentScreenPersonalDataCheckbox
  case consentScreenTitle
  case consentScreenTosButton
  case consentScreenTosCheckbox
  case contentDescriptionAddDocumentFromQrIcon
  case contentDescriptionAddIcon
  case contentDescriptionArrowBackIcon
  case contentDescriptionArrowDownIcon
  case contentDescriptionArrowRightIcon
  case contentDescriptionArrowUpIcon
  case contentDescriptionCheckIcon
  case contentDescriptionClockTimerIcon
  case contentDescriptionCloseIcon
  case contentDescriptionDateRangeIcon
  case contentDescriptionDocumentsIcon
  case contentDescriptionEditIcon
  case contentDescriptionErrorIcon
  case contentDescriptionEuFlagIcon
  case contentDescriptionEuMapIcon
  case contentDescriptionFiltersIcon
  case contentDescriptionHandleBarIcon
  case contentDescriptionIdIcon
  case contentDescriptionImageOrPlaceholderIcon
  case contentDescriptionInProgressIcon
  case contentDescriptionInfoIcon
  case contentDescriptionIssuerLogoIcon
  case contentDescriptionLogoPlainIcon
  case contentDescriptionLogoTextIcon
  case contentDescriptionMessageIcon
  case contentDescriptionMoreVertIcon
  case contentDescriptionNationalEidIcon
  case contentDescriptionOpenNewIcon
  case contentDescriptionOver18Icon
  case contentDescriptionPresentDocumentSameDeviceIcon
  case contentDescriptionQrIcon
  case contentDescriptionQrScannerIcon
  case contentDescriptionScytalesLogoIcon
  case contentDescriptionSearchIcon
  case contentDescriptionSettingsIcon
  case contentDescriptionSuccessIcon
  case contentDescriptionTelekomLogoIcon
  case contentDescriptionTouchIdIcon
  case contentDescriptionUserIcon
  case contentDescriptionVerifiedIcon
  case contentDescriptionWalletActivatedIcon
  case contentDescriptionWalletSecuredIcon
  case contentDescriptionWarningIcon
  case documentCategoryEducation
  case documentCategoryFinance
  case documentCategoryGovernment
  case documentCategoryHealth
  case documentCategoryOther
  case documentCategoryRetail
  case documentCategorySocialSecurity
  case documentCategoryTravel
  case documentDetailsBooleanItemFalseReadableValue
  case documentDetailsBooleanItemTrueReadableValue
  case documentSuccessCollapsedSupportingText
  case documentSuccessHeaderDescription
  case documentSuccessHeaderDescriptionWhenError
  case documentSuccessRelyingPartyDefaultName
  case documentSuccessStickyButtonText
  case genericCancel
  case genericCancelCapitalized
  case genericClose
  case genericContinueCapitalized
  case genericDefaultIssuerName
  case genericDefaultRelyingPartyName
  case genericDeferredSuccessText
  case genericErrorButtonRetry
  case genericErrorDescription
  case genericErrorMessage
  case genericErrorRetry
  case genericNetworkErrorMessage
  case genericOk
  case genericOr
  case genericScanQr
  case genericSuccess
  case genericViewDetails
  case issuanceAddDocumentDeferredSuccessDescription
  case issuanceAddDocumentDeferredSuccessPrimaryButtonText
  case issuanceAddDocumentDeferredSuccessText
  case issuanceAddDocumentNoOptions
  case issuanceAddDocumentScanQrFooterButtonText
  case issuanceAddDocumentScanQrFooterText
  case issuanceAddDocumentSubtitle
  case issuanceAddDocumentTitle
  case issuanceCodeCaption([String])
  case issuanceCodeTitle([String])
  case issuanceDocumentOfferDeferredSuccessDescription([String])
  case issuanceDocumentOfferDeferredSuccessDescriptionWithDoc([String])
  case issuanceDocumentOfferDeferredSuccessDescriptionWithDocAndIssuer([String])
  case issuanceDocumentOfferDeferredSuccessPrimaryButtonText
  case issuanceDocumentOfferDeferredSuccessText
  case issuanceDocumentOfferDescription
  case issuanceDocumentOfferErrorInvalidTxcodeFormat([String])
  case issuanceDocumentOfferErrorMissingPidText
  case issuanceDocumentOfferErrorNoDocument
  case issuanceDocumentOfferHeaderMainText
  case issuanceDocumentOfferPrimaryButtonTextAdd
  case issuanceDocumentOfferRelyingPartyDefaultName
  case issuanceDocumentOfferRelyingPartyDescription([String])
  case issuanceGenericError
  case issuanceQrScanSubtitle
  case issuanceQrScanTitle
  case issuanceSuccessHeaderDescription
  case issuanceSuccessHeaderDescriptionWhenError
  case issuanceSuccessHeaderIssuerDefaultName
  case labelClose
  case labelTurnOn
  case landingScreenAddCredentials
  case landingScreenCardAgeVerification
  case landingScreenCardEuTitle
  case landingScreenCredentialDetails
  case landingScreenCredentialsLeft(Int)
  case landingScreenNoAgeCredentialFound
  case landingScreenPrimaryButtonLabelScan
  case landingScreenSubtitle
  case landingScreenTitle
  case loadingBiometryBiometricsEnabledDescription
  case loadingBiometryBiometricsNotEnabledDescription
  case loadingHeaderDescription
  case nfcBodyInitial
  case nfcBodyReading
  case nfcHelpLink
  case nfcTitle
  case nfcTitleInitial
  case nfcTitleReading
  case onboardingStep1Title
  case onboardingStep2Title
  case onboardingStep3Title
  case onboardingStep4Title
  case onboardingVerificationDescription
  case onboardingVerificationNationalId
  case onboardingVerificationNationalIdDescription
  case onboardingVerificationPassportIdCard
  case onboardingVerificationPassportIdCardDescription
  case onboardingVerificationTitle
  case passportBiometrics
  case passportBiometricsBack
  case passportBiometricsContentDescription
  case passportBiometricsDob
  case passportBiometricsDoe
  case passportBiometricsFirstDescription
  case passportBiometricsFirstHeader
  case passportBiometricsFirstLink
  case passportBiometricsNext
  case passportBiometricsNoAvailability
  case passportBiometricsNoPassportData
  case passportBiometricsPassport
  case passportBiometricsScanCancelled
  case passportBiometricsTryAgain
  case passportBiometricsUnknownError
  case passportBiometricsVerifyData
  case passportCaptureSubtitle
  case passportCaptureTitle
  case passportCredentialIssuanceDescription
  case passportCredentialIssuanceTitle
  case passportIdentification
  case passportIdentificationBack
  case passportIdentificationCapture
  case passportIdentificationDescription
  case passportIdentificationFooter
  case passportIdentificationStepFirst
  case passportIdentificationStepSecond
  case passportIdentificationTitle
  case passportLiveVideo
  case passportLiveVideoBack
  case passportLiveVideoDescription
  case passportLiveVideoDownloadingProgress
  case passportLiveVideoErrorNotLive
  case passportLiveVideoErrorNotMatching
  case passportLiveVideoErrorNotProcessed
  case passportLiveVideoFooter
  case passportLiveVideoHeader
  case passportLiveVideoLiveCapture
  case passportLiveVideoStepFirst
  case passportLiveVideoStepSecond
  case passportLiveVideoStepThird
  case passportScanIntroBackButton
  case passportScanIntroDataDownloadNotice
  case passportScanIntroDescription
  case passportScanIntroEnrollmentMethod
  case passportScanIntroStartButton
  case passportScanIntroStep1Description
  case passportScanIntroStep1Title
  case passportScanIntroStep2Description
  case passportScanIntroStep2Title
  case passportScanIntroStep3Description
  case passportScanIntroStep3Title
  case passportScanIntroStep4Title
  case passportScanIntroStep5Title
  case passportScanIntroTitle
  case passportValidationErrorExpired
  case passportValidationErrorIncompleteData
  case passportValidationErrorUnderage
  case presentationQrScanSubtitle
  case presentationQrScanTitle
  case qrScanInformativeTextIssuanceFlow
  case qrScanInformativeTextPresentationFlow
  case qrScanPermissionNotGranted
  case quickPinBottomSheetCancelPrimaryButtonText
  case quickPinBottomSheetCancelSecondaryButtonText
  case quickPinBottomSheetCancelSubtitle
  case quickPinBottomSheetCancelTitle
  case quickPinChangeEnterNewSubtitle
  case quickPinChangeLockoutCountdownMinutes(Int, Int)
  case quickPinChangeLockoutCountdownSeconds(Int)
  case quickPinChangeReenterNewSubtitle
  case quickPinChangeSuccessBtn
  case quickPinChangeSuccessDescription
  case quickPinChangeSuccessText
  case quickPinChangeTitle
  case quickPinChangeValidateCurrentSubtitle
  case quickPinConfirmButton
  case quickPinCreateEnterSubtitle
  case quickPinCreateReenterSubtitle
  case quickPinCreateReenterTitle
  case quickPinCreateTitle
  case quickPinInvalidError
  case quickPinInvalidGenericError
  case quickPinInvalidLastAttempt
  case quickPinInvalidWithAttempts(Int)
  case quickPinLockedOut
  case quickPinLockoutCountdownMinutes(Int, Int)
  case quickPinLockoutCountdownSeconds(Int)
  case quickPinNextButton
  case quickPinNonMatch
  case quickPinNumericalRuleInvalidErrorMessage
  case requestBottomSheetWarningSubtitle
  case requestBottomSheetWarningTitle
  case requestCollapsedSupportingText
  case requestGenderFemale
  case requestGenderMale
  case requestGenderNotApplicable
  case requestGenderNotKnown
  case requestHeaderDescription
  case requestHeaderMainText
  case requestNoData
  case requestRelyingPartyDefaultName
  case requestRelyingPartyDescription([String])
  case requestStickyButtonText
  case requestWarningText
  case requiredNfcNotSupported
  case requiredPermsNotGiven
  case settings
  case settingsScreenAppInfo
  case settingsScreenChangePin
  case settingsScreenCredentials
  case settingsScreenDeleteProofs
  case settingsScreenSecurity
  case settingsScreenTitle
  case settingsScreenVersion
  case splashScreenSponsors
  case splashScreenTitle
  case warningAuthenticationFailed
  case warningClaNotSupported
  case warningEnableNfc
  case welcomePage1
  case welcomePage2
  case welcomePage3
  case welcomeScreenNext
  case welcomeScreenSkip
  case welcomeTitle1
  case welcomeTitle2
  case welcomeTitle3

  // Additional Keys apart from Android
  case mrzErrorInvalidData
  case mrzErrorDocumentExpired
  case mrzErrorProcessingFailed

  case mrzInitializingCamera
  case mrzCameraPermissionDenied
  case mrzCameraSetupFailed
  case mrzUnknownError

  case mrzDocumentReady
  case mrzScanning
  case mrzCameraError

  // NFC Errors
  case nfcErrorTagNotValid
  case nfcErrorMoreThanOneTag
  case nfcErrorConnection
  case nfcErrorUserCanceled
  case nfcErrorInvalidMRZKey
  case nfcErrorUnexpected
  case nfcErrorReadingFailed
  case nfcErrorMissingData

  // Extra after merge
  case itemNotFoundInStorage
  case itemsNotFoundInStorage
  case unknownVerifier
  case requestDataInfoNotice
  case issuanceDocumentOfferErrorUnableToPresentAndShare
  case issuanceDocumentOfferErrorUnableToFetchTransactionLog
  case genericUnknown
  case requestDataVerifiedEntityMessage
  case openSystemSettings
  case quickPinChangeHelpText
  case biometricConfirmRequest
  case proximityConnectivityCaption
  case proximityConnectionBleDescription
  case documentProviderSectionHeader
  case genericAccept

}

public extension LocalizableStringKey {
  var toString: String {
    LocalizableManager.shared.get(with: self)
  }
  var toLocalizedStringKey: LocalizedStringKey {
    LocalizedStringKey(self.toString)
  }
}
