/*
 * Copyright (c) 2025 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work
 * except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the Licence for the specific language
 * governing permissions and limitations under the Licence.
 */
import SwiftUI

public enum LocalizableStringKey: Equatable, Sendable {
  case dynamic(key: String)
  case custom(String)
  case space
  case ageOver18
  case ageOver(Int)
  case biometricConfirmRequest
  case biometricDefaultModeTextAbovePinField
  case biometricLoginBiometricsEnabledSubtitle
  case biometricLoginBiometricsNotEnabledSubtitle
  case biometricLoginForgotPin
  case biometricLoginTitle
  case biometricNoHardware
  case biometricPromptSubtitle
  case biometricPromptTitle
  case biometricSetupDescription(String)
  case biometricSetupEnable
  case biometricSetupSkip
  case biometricSetupTitle
  case biometricUnknownError
  case biometryUnlockReason
  case cdCloseButton
  case cdFlashButton
  case confirmDocRemovalDialogDelete
  case confirmDocRemovalDialogText
  case confirmDocRemovalDialogTitle
  case consentScreenConfirmButton
  case consentScreenDataProtectionButton
  case consentScreenDataProtectionCheckbox
  case consentScreenPersonalDataCheckbox
  case consentScreenTitle
  case consentScreenTosButton
  case consentScreenTosCheckbox
  case contentDescriptionAddDocumentFromQrIcon
  case contentDescriptionAddIcon
  case contentDescriptionArrowBackIcon
  case contentDescriptionArrowDownIcon
  case contentDescriptionArrowRightIcon
  case contentDescriptionArrowUpIcon
  case contentDescriptionCheckIcon
  case contentDescriptionClockTimerIcon
  case contentDescriptionCloseIcon
  case contentDescriptionDateRangeIcon
  case contentDescriptionDocumentsIcon
  case contentDescriptionEditIcon
  case contentDescriptionErrorIcon
  case contentDescriptionEuFlagIcon
  case contentDescriptionEuMapIcon
  case contentDescriptionFiltersIcon
  case contentDescriptionHandleBarIcon
  case contentDescriptionIdIcon
  case contentDescriptionImageOrPlaceholderIcon
  case contentDescriptionInProgressIcon
  case contentDescriptionInfoIcon
  case contentDescriptionIssuerLogoIcon
  case contentDescriptionLogoPlainIcon
  case contentDescriptionLogoTextIcon
  case contentDescriptionMessageIcon
  case contentDescriptionMoreVertIcon
  case contentDescriptionNationalEidIcon
  case contentDescriptionOpenNewIcon
  case contentDescriptionOver18Icon
  case contentDescriptionPresentDocumentSameDeviceIcon
  case contentDescriptionQrIcon
  case contentDescriptionQrScannerIcon
  case contentDescriptionScytalesLogoIcon
  case contentDescriptionSearchIcon
  case contentDescriptionSettingsIcon
  case contentDescriptionSuccessIcon
  case contentDescriptionTelekomLogoIcon
  case contentDescriptionTouchIdIcon
  case contentDescriptionUserIcon
  case contentDescriptionVerifiedIcon
  case contentDescriptionWalletActivatedIcon
  case contentDescriptionWalletSecuredIcon
  case contentDescriptionWarningIcon
  case documentCategoryEducation
  case documentCategoryFinance
  case documentCategoryGovernment
  case documentCategoryHealth
  case documentCategoryOther
  case documentCategoryRetail
  case documentCategorySocialSecurity
  case documentCategoryTravel
  case documentDetailsBooleanItemFalseReadableValue
  case documentDetailsBooleanItemTrueReadableValue
  case documentProviderSectionHeader
  case documentSuccessCollapsedSupportingText
  case documentSuccessHeaderDescription
  case documentSuccessHeaderDescriptionWhenError
  case documentSuccessRelyingPartyDefaultName
  case documentSuccessStickyButtonText
  case genericAccept
  case genericBack
  case genericCancel
  case genericCancelCapitalized
  case genericClose
  case genericContinueCapitalized
  case genericDefaultIssuerName
  case genericDefaultRelyingPartyName
  case genericDeferredSuccessText
  case genericErrorButtonRetry
  case genericErrorDescription
  case genericErrorMessage
  case genericErrorRetry
  case genericNetworkErrorMessage
  case genericNo
  case genericOk
  case genericOr
  case genericScanQr
  case genericSuccess
  case genericUnknown
  case genericViewDetails
  case genericYes
  case issuanceAddDocumentDeferredSuccessDescription
  case issuanceAddDocumentDeferredSuccessPrimaryButtonText
  case issuanceAddDocumentDeferredSuccessText
  case issuanceAddDocumentNoOptions
  case issuanceAddDocumentScanQrFooterButtonText
  case issuanceAddDocumentScanQrFooterText
  case issuanceAddDocumentSubtitle
  case issuanceAddDocumentTitle
  case issuanceCodeCaption(Int)
  case issuanceCodeTitle(String)
  case issuanceDocumentOfferDeferredSuccessDescription(String)
  case issuanceDocumentOfferDeferredSuccessDescriptionWithDoc(String)
  case issuanceDocumentOfferDeferredSuccessDescriptionWithDocAndIssuer(String, String)
  case issuanceDocumentOfferDeferredSuccessPrimaryButtonText
  case issuanceDocumentOfferDeferredSuccessText
  case issuanceDocumentOfferDescription
  case issuanceDocumentOfferErrorInvalidTxcodeFormat(Int, Int)
  case issuanceDocumentOfferErrorMissingPidText
  case issuanceDocumentOfferErrorNoDocument
  case issuanceDocumentOfferErrorUnableToFetchTransactionLog
  case issuanceDocumentOfferErrorUnableToPresentAndShare
  case issuanceDocumentOfferHeaderMainText
  case issuanceDocumentOfferPrimaryButtonTextAdd
  case issuanceDocumentOfferRelyingPartyDefaultName
  case issuanceDocumentOfferRelyingPartyDescription
  case issuanceGenericError
  case issuanceQrScanSubtitle
  case issuanceQrScanTitle
  case issuanceSuccessHeaderDescription
  case issuanceSuccessHeaderDescriptionWhenError
  case issuanceSuccessHeaderIssuerDefaultName
  case issueDocumentPrompt
  case itemNotFoundInStorage
  case itemsNotFoundInStorage
  case labelClose
  case labelTurnOn
  case landingScreenAddCredentials
  case landingScreenCardAgeVerification
  case landingScreenCardEuTitle
  case landingScreenCredentialDetails
  case landingScreenCredentialsLeft(Int)
  case landingScreenNoAgeCredentialFound
  case landingScreenPrimaryButtonLabelScan
  case landingScreenSubtitle
  case landingScreenTitle
  case loadingBiometryBiometricsEnabledDescription
  case loadingBiometryBiometricsNotEnabledDescription
  case loadingHeaderDescription
  case mrzCameraError
  case mrzCameraPermissionDenied
  case mrzCameraSetupFailed
  case mrzDocumentReady
  case mrzErrorDocumentExpired
  case mrzErrorInvalidData
  case mrzErrorProcessingFailed
  case mrzInitializingCamera
  case mrzScanning
  case mrzUnknownError
  case nfcBodyInitial
  case nfcBodyReading
  case nfcErrorConnection
  case nfcErrorInvalidMrzKey
  case nfcErrorMissingData
  case nfcErrorMoreThanOneTag
  case nfcErrorReadingFailed
  case nfcErrorReadingTag
  case nfcErrorTagNotValid
  case nfcErrorUnexpected
  case nfcErrorUserCanceled
  case nfcHelpLink
  case nfcTitle
  case nfcTitleInitial
  case nfcTitleReading
  case onboardingStep1Title
  case onboardingStep2Title
  case onboardingStep3Title
  case onboardingStep4Title
  case onboardingTokenQrIntroTitle
  case onboardingTokenQrIntroDescription
  case onboardingVerificationTokenQr
  case onboardingVerificationTokenQrDescription
  case onboardingVerificationDescription
  case onboardingVerificationNationalId
  case onboardingVerificationNationalIdDescription
  case onboardingVerificationNationalIdHint
  case onboardingVerificationPassportIdCard
  case onboardingVerificationPassportIdCardDescription
  case onboardingVerificationTitle
  case openSystemSettings
  case passportBiometrics
  case passportBiometricsBack
  case passportBiometricsContentDescription
  case passportBiometricsDob
  case passportBiometricsDoe
  case passportBiometricsFirstDescription
  case passportBiometricsFirstHeader
  case passportBiometricsFirstLink
  case passportBiometricsNext
  case passportBiometricsNoAvailability
  case passportBiometricsNoPassportData
  case passportBiometricsPassport
  case passportBiometricsScanCancelled
  case passportBiometricsTryAgain
  case passportBiometricsUnknownError
  case passportBiometricsVerifyData
  case passportCaptureSubtitle
  case passportCaptureTitle
  case passportCredentialIssuanceDescription
  case passportCredentialIssuanceTitle
  case passportIdentification
  case passportIdentificationBack
  case passportIdentificationCapture
  case passportIdentificationDescription
  case passportIdentificationFooter
  case passportIdentificationStepFirst
  case passportIdentificationStepSecond
  case passportIdentificationTitle
  case passportLiveVideo
  case passportLiveVideoBack
  case passportLiveVideoDescription
  case passportLiveVideoDownloadingProgress(Int, String)
  case passportLiveVideoErrorNotLive
  case passportLiveVideoErrorNotMatching
  case passportLiveVideoErrorNotProcessed
  case passportLiveVideoFooter
  case passportLiveVideoHeader
  case passportLiveVideoLiveCapture
  case passportLiveVideoStepFirst
  case passportLiveVideoStepSecond
  case passportLiveVideoStepThird
  case passportScanIntroBackButton
  case passportScanIntroDataDownloadNotice
  case passportScanIntroDescription
  case passportScanIntroEnrollmentMethod
  case passportScanIntroStartButton
  case passportScanIntroStep1Description
  case passportScanIntroStep1Title
  case passportScanIntroStep2Description
  case passportScanIntroStep2Title
  case passportScanIntroStep3Description
  case passportScanIntroStep3Title
  case passportScanIntroStep4Title
  case passportScanIntroStep5Title
  case passportScanIntroTitle
  case passportValidationErrorExpired
  case passportValidationErrorIncompleteData
  case passportValidationErrorUnderage
  case presentationQrScanSubtitle
  case presentationQrScanTitle
  case proximityConnectionBleDescription
  case proximityConnectivityCaption
  case qrScanInformativeTextIssuanceFlow
  case qrScanInformativeTextPresentationFlow
  case qrScanPermissionNotGranted
  case quickPinBottomSheetCancelPrimaryButtonText
  case quickPinBottomSheetCancelSecondaryButtonText
  case quickPinBottomSheetCancelSubtitle
  case quickPinBottomSheetCancelTitle
  case quickPinCantUsePreviousPin
  case quickPinChangeEnterNewSubtitle
  case quickPinChangeHelpText
  case quickPinChangeLockoutCountdownMinutes(Int, Int)
  case quickPinChangeLockoutCountdownSeconds(Int)
  case quickPinChangeReenterNewSubtitle
  case quickPinChangeSuccessBtn
  case quickPinChangeSuccessDescription
  case quickPinChangeSuccessText
  case quickPinChangeTitle
  case quickPinChangeValidateCurrentSubtitle
  case quickPinConfirmButton
  case quickPinCreateEnterSubtitle
  case quickPinCreateReenterSubtitle
  case quickPinCreateReenterTitle
  case quickPinCreateTitle
  case quickPinInvalidError
  case quickPinInvalidGenericError
  case quickPinInvalidLastAttempt
  case quickPinInvalidWithAttempts(Int)
  case quickPinLockedOut
  case quickPinLockoutCountdownMinutes(Int, Int)
  case quickPinLockoutCountdownSeconds(Int)
  case quickPinNextButton
  case quickPinNonMatch
  case quickPinNumericalRuleInvalidErrorMessage
  case requestBottomSheetWarningSubtitle
  case requestBottomSheetWarningTitle
  case requestCollapsedSupportingText
  case requestDataInfoNotice
  case requestDataVerifiedEntityMessage
  case requestGenderFemale
  case requestGenderMale
  case requestGenderNotApplicable
  case requestGenderNotKnown
  case requestHeaderDescription
  case requestHeaderMainText
  case requestNoData
  case requestRelyingPartyDefaultName
  case requestRelyingPartyDescription
  case requestStickyButtonText
  case requestWarningText
  case requiredNfcNotSupported
  case requiredPermsNotGiven
  case settings
  case settingsScreenAppInfo
  case settingsScreenChangePin
  case settingsScreenCredentials
  case settingsScreenDeleteProofs
  case settingsScreenSecurity
  case settingsScreenTitle
  case settingsScreenVersion
  case splashScreenSponsors
  case splashScreenTitle
  case unknownVerifier
  case unsupportedDeviceMessage
  case unsupportedDeviceTitle
  case warningAuthenticationFailed
  case warningClaNotSupported
  case warningEnableNfc
  case welcomePage1
  case welcomePage2
  case welcomePage3
  case welcomeScreenNext
  case welcomeScreenSkip
  case welcomeTitle1
  case welcomeTitle2
  case welcomeTitle3
}

public extension LocalizableStringKey {
  var toString: String {
    LocalizableManager.shared.get(with: self)
  }
  var toLocalizedStringKey: LocalizedStringKey {
    LocalizedStringKey(self.toString)
  }
}
